name: FakeMobs
version: 1.9.4
author: Howaner
description: A simple npc plugin
depend: [ProtocolLib]
main: de.howaner.FakeMobs.FakeMobsPlugin

commands:
  FakeMob:
    description: FakeMobs Manage
    usage: "ยง4Bad Syntax. Type /FakeMob help for Help!"
permissions:
  FakeMobs.reload:
    description: Reload the plugin
    default: op
  FakeMobs.create:
    description: Spawn Fake Mobs
    default: op
  FakeMobs.select:
    description: Select Fake Mobs
    default: op
  FakeMobs.name:
    description: Give Fake Mob a name
    default: op
  FakeMobs.sitting:
    description: Can sit the Fake Mob
    default: op
  FakeMobs.gliding:
    description: Make a fake player to gliding
    default: op
  FakeMobs.layer:
    description: Show/Hide second skin layer
    default: op
  FakeMobs.invisibility:
    description: Can make a Fake Mob Invisibility
    default: op
  FakeMobs.look:
    description: Can change the look Function of a Mob
    default: op
  FakeMobs.teleport:
    description: Teleport a Fake Mob
    default: op
  FakeMobs.inv:
    description: Can edit the Inventory of a Fake Mob
    default: op
  FakeMobs.shop:
    description: Permission to manage the Shop of a Fake mob
    default: op
  FakeMobs.interact:
    description: Permission to manage the Interact Actions of a Fake mob
    default: op
  FakeMobs.skin:
    description: Permission to set the skin from a player
    default: op
  FakeMobs.remove:
    description: Remove Fake Mobs
    default: op
  FakeMobs.help:
    description: Can see the Help page
  FakeMobs.*:
    description: All Permissions for FakeMobs
    children:
      FakeMobs.create: true
      FakeMobs.select: true
      FakeMobs.name: true
      FakeMobs.sitting: true
      FakeMobs.invisibility: true
      FakeMobs.look: true
      FakeMobs.teleport: true
      FakeMobs.inv: true
      FakeMobs.shop: true
      FakeMobs.interact: true
      FakeMobs.skin: true
      FakeMobs.remove: true
      FakeMobs.help: true
    default: op
